import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Building2, Check, ChevronLeft, ChevronRight, ClipboardList, FileCheck2, Landmark, LayoutDashboard, LogOut, Plus, ShieldCheck, Users, X } from 'lucide-react';
import type { AuditEvent, Committee, Grant, GrantRequest, Municipality, Page, Permission, Person, SessionView, Term, User } from '@ltas/contracts';
import { ApiError, request } from './api';

type View='overview'|'municipality'|'terms'|'people'|'committees'|'users'|'access'|'audit';
const navigation:Array<{id:View;label:string;icon:typeof Users;permission?:Permission}>=[
  {id:'overview',label:'Overview',icon:LayoutDashboard}, {id:'municipality',label:'Municipality',icon:Building2,permission:'municipality.view'},
  {id:'terms',label:'Council terms',icon:Landmark,permission:'term.view'}, {id:'people',label:'People',icon:Users,permission:'person.view'},
  {id:'committees',label:'Committees',icon:ClipboardList,permission:'committee.view'}, {id:'users',label:'User accounts',icon:Users,permission:'user.view'},
  {id:'access',label:'Access review',icon:ShieldCheck,permission:'role.assign'}, {id:'audit',label:'Audit trail',icon:FileCheck2,permission:'audit.view'},
];
const labels:Record<View,string>={overview:'Your municipal workspace',municipality:'Municipality',terms:'Council terms',people:'People & officeholders',committees:'Committee directory',users:'User accounts',access:'Access review',audit:'Audit trail'};
const date=(v:string)=>new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeZone:'Asia/Manila'}).format(new Date(v));
function Notice({error}:{error:unknown}) {return <div className="notice error" role="alert">{error instanceof Error?error.message:'This request could not be completed.'}{error instanceof ApiError && <small>Reference: {error.problem.correlationId}</small>}</div>;}
function Empty({children}:{children:ReactNode}) {return <div className="empty"><ClipboardList size={28}/><p>{children}</p></div>;}
function Status({value}:{value:string}) {return <span className={`badge ${['APPROVED','Active','DELIVERED'].includes(value)?'green':value==='PENDING'?'amber':''}`}>{value.toLowerCase().replaceAll('_',' ')}</span>;}
interface Field {name:string;label:string;type?:string;options?:Array<{value:string;label:string}>;defaultValue?:string;minLength?:number;}
function CommandForm({title,path,csrf,fields,method='POST',fixed={},transform,onDone}:{title:string;path:string;csrf:string;fields:Field[];method?:string;fixed?:Record<string,unknown>;transform?:(body:Record<string,unknown>)=>Record<string,unknown>;onDone?:()=>void}) {
  const cache=useQueryClient(),form=useRef<HTMLFormElement>(null),retry=useRef<{body:string;key:string}|null>(null);
  const mutation=useMutation({mutationFn:(body:Record<string,unknown>)=>{
    const serialized=JSON.stringify(body);
    if(retry.current?.body!==serialized) retry.current={body:serialized,key:crypto.randomUUID()};
    return request(path,{method,body,csrf,key:retry.current.key});
  },onSuccess:()=>{retry.current=null;form.current?.reset();void cache.invalidateQueries();onDone?.();}});
  function submit(e:FormEvent<HTMLFormElement>) {e.preventDefault();const body={...Object.fromEntries(new FormData(e.currentTarget)),...fixed};mutation.mutate(transform?transform(body):body);}
  return <form ref={form} className="command-form" onSubmit={submit}><h3>{title}</h3><div className="form-grid">{fields.map(field=><label key={field.name}>{field.label}{field.options?<select required name={field.name} defaultValue={field.defaultValue??''}><option value="" disabled>Select…</option>{field.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input required name={field.name} type={field.type??'text'} defaultValue={field.defaultValue} minLength={field.minLength} maxLength={field.name==='reason'?500:255}/>}</label>)}</div><label>Reason for this change<textarea required name="reason" minLength={8} maxLength={500} placeholder="Explain the change for the audit record."/></label>{mutation.isError&&<Notice error={mutation.error}/>} {mutation.isSuccess&&<p className="success" role="status"><Check size={16}/> Change saved and recorded.</p>}<button className="primary" disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save change'}<ArrowRight size={16}/></button></form>;
}
function AddPanel({label,children}:{label:string;children:ReactNode}) {return <details className="add-panel"><summary><Plus size={16}/>{label}</summary>{children}</details>;}
function Listing<T>({path,children}:{path:string;children:(items:T[])=>ReactNode}) {
  const [page,setPage]=useState(1);const query=useQuery({queryKey:[path,page],queryFn:()=>request<Page<T>>(`${path}?page=${page}&limit=25`)});
  return <>{query.isPending?<p role="status">Loading records…</p>:query.isError?<Notice error={query.error}/>:<>{query.data.items.length?children(query.data.items):<Empty>No records to display.</Empty>}<div className="pagination"><span>{query.data.pageInfo.total} records · Page {page}</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/></button><button aria-label="Next page" disabled={page*25>=query.data.pageInfo.total} onClick={()=>setPage(p=>p+1)}><ChevronRight size={16}/></button></div></div></>}</>;
}
function Table({head,children}:{head:string[];children:ReactNode}) {return <div className="table-scroll"><table><thead><tr>{head.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function MunicipalityPage({session}:{session:SessionView}) {
  const query=useQuery({queryKey:['/admin/municipality'],queryFn:()=>request<{data:Municipality}>('/admin/municipality')});
  if(query.isError)return <Notice error={query.error}/>;if(!query.data)return <p>Loading municipality…</p>;const m=query.data.data;
  return <><div className="record-heading"><Building2 size={32}/><div><h2>{m.name}</h2><p>{m.province} · {m.timezone}</p></div><Status value={m.code}/></div><dl className="facts"><div><dt>Installation</dt><dd>Single municipality</dd></div><div><dt>Data</dt><dd>Fictional development records</dd></div><div><dt>Record revision</dt><dd>{m.revision}</dd></div></dl>{session.permissions.includes('settings.manage')&&<CommandForm key={m.revision} title="Update municipality details" path="/admin/municipality" method="PATCH" csrf={session.csrfToken} fixed={{expectedRevision:m.revision}} fields={[{name:'name',label:'Municipality name',defaultValue:m.name},{name:'province',label:'Province',defaultValue:m.province}]}/>}</>;
}
function TermsPage({session}:{session:SessionView}) {return <>{session.permissions.includes('term.manage')&&<AddPanel label="Add council term"><CommandForm title="New council term" path="/admin/terms" csrf={session.csrfToken} fields={[{name:'label',label:'Term label'},{name:'startsOn',label:'Start date',type:'date'},{name:'endsOn',label:'End date',type:'date'}]}/></AddPanel>}<Listing<Term> path="/admin/terms">{items=><Table head={['Council term','Starts','Ends','Revision']}>{items.map(t=><tr key={t.id}><td><strong>{t.label}</strong></td><td>{date(t.startsOn)}</td><td>{date(t.endsOn)}</td><td>{t.revision}</td></tr>)}</Table>}</Listing></>;}
function PeoplePage({session}:{session:SessionView}) {return <><p className="lead">Historical people are preserved independently of login accounts.</p>{session.permissions.includes('person.manage')&&<AddPanel label="Add person"><CommandForm title="New person" path="/admin/persons" csrf={session.csrfToken} fields={[{name:'displayName',label:'Full display name'}]}/></AddPanel>}<Listing<Person> path="/admin/persons">{items=><Table head={['Name','Record ID']}>{items.map(p=><tr key={p.id}><td><strong>{p.displayName}</strong></td><td className="mono">{p.id}</td></tr>)}</Table>}</Listing></>;}
function CommitteeDetail({id,session,onBack}:{id:string;session:SessionView;onBack:()=>void}) {
  const query=useQuery({queryKey:['/committees',id],queryFn:()=>request<{data:Committee}>(`/committees/${id}`)});
  const canEdit=session.permissions.includes('committee.members.manage');
  const people=useQuery({queryKey:['/admin/persons','options'],queryFn:()=>request<Page<Person>>('/admin/persons?limit=100'),enabled:canEdit});
  if(query.isError)return <Notice error={query.error}/>;if(!query.data)return <p>Loading committee…</p>;const c=query.data.data;
  return <><button className="text-button" onClick={onBack}><ChevronLeft size={16}/>All committees</button><h2>{c.name}</h2><p className="lead">{c.code} · {c.term?.label}</p>{canEdit&&(people.isError?<Notice error={people.error}/>:<AddPanel label="Assign committee member"><CommandForm key={c.revision} title="New membership" path={`/committees/${id}/members`} csrf={session.csrfToken} fixed={{expectedRevision:c.revision}} fields={[{name:'personId',label:'Person',options:people.data?.items.map(p=>({value:p.id,label:p.displayName}))??[]},{name:'role',label:'Committee role',options:['CHAIR','VICE_CHAIR','MEMBER','STAFF'].map(value=>({value,label:value.replace('_',' ')}))},{name:'startsOn',label:'Start date',type:'date'},{name:'endsOn',label:'End date',type:'date'}]}/></AddPanel>)}<Table head={['Member','Role','From','Until']}>{c.members?.map(m=><tr key={m.id}><td><strong>{m.person?.displayName}</strong></td><td><Status value={m.role}/></td><td>{date(m.startsOn)}</td><td>{date(m.endsOn)}</td></tr>)}</Table>{!c.members?.length&&<Empty>No committee members assigned.</Empty>}</>;
}
function CommitteesPage({session}:{session:SessionView}) {
  const [selected,setSelected]=useState<string|null>(null),canEdit=session.permissions.includes('committee.manage');
  const terms=useQuery({queryKey:['/admin/terms','options'],queryFn:()=>request<Page<Term>>('/admin/terms?limit=100'),enabled:canEdit});
  if(selected)return <CommitteeDetail id={selected} session={session} onBack={()=>setSelected(null)}/>;
  return <>{canEdit&&(terms.isError?<Notice error={terms.error}/>:<AddPanel label="Create committee"><CommandForm title="New committee" path="/committees" csrf={session.csrfToken} fields={[{name:'name',label:'Committee name'},{name:'code',label:'Code (uppercase letters, numbers, hyphens)'},{name:'termId',label:'Council term',options:terms.data?.items.map(t=>({value:t.id,label:t.label}))??[]}]}/></AddPanel>)}<Listing<Committee> path="/committees">{items=><div className="committee-grid">{items.map(c=><button className="committee-card" key={c.id} onClick={()=>setSelected(c.id)}><span className="card-icon"><ClipboardList size={23}/></span><span className="eyebrow">{c.code}</span><h3>{c.name}</h3><p>{c.term?.label}</p><span className="card-link">View roster <ArrowRight size={16}/></span></button>)}</div>}</Listing></>;
}
function UsersPage({session}:{session:SessionView}) {return <><p className="lead">Link an existing Keycloak identity. Credentials remain with the identity service.</p><AddPanel label="Link user account"><CommandForm title="Link identity" path="/admin/users" csrf={session.csrfToken} fields={[{name:'displayName',label:'Display name'},{name:'subject',label:'Keycloak user ID (subject)'}]}/></AddPanel><Listing<User> path="/admin/users">{items=><Table head={['User','Status','Access action']}>{items.map(u=><tr key={u.id}><td><strong>{u.displayName}</strong><small className="mono">{u.subject}</small></td><td><Status value={u.enabled?'Active':'Disabled'}/></td><td>{u.id!==session.user.id?<AddPanel label={u.enabled?'Disable account':'Enable account'}><CommandForm title={`${u.enabled?'Disable':'Enable'} ${u.displayName}`} path={`/admin/users/${u.id}/state`} method="PATCH" csrf={session.csrfToken} fields={[]} fixed={{enabled:!u.enabled,expectedRevision:u.revision}}/></AddPanel>:<span className="muted">Your account</span>}</td></tr>)}</Table>}</Listing></>;}
function AccessPage({session}:{session:SessionView}) {
  const users=useQuery({queryKey:['/admin/users','options'],queryFn:()=>request<Page<User>>('/admin/users?limit=100')});
  const [role,setRole]=useState('SEC');
  // A SYS can request committee access using an exact committee ID, without gaining committee record access.
  return <><div className="notice"><ShieldCheck size={20}/><span>Access grants require two administrators. Requester, reviewer, and recipient must be different people.</span></div><AddPanel label="Request access grant"><label className="role-select">Role<select value={role} onChange={e=>setRole(e.target.value)}>{['SYS','SEC','AUD','CS'].map(r=><option key={r}>{r}</option>)}</select></label>{users.isError?<Notice error={users.error}/>:<CommandForm key={role} title="Access request" path="/admin/grant-requests" csrf={session.csrfToken} fixed={{role,scopeType:role==='CS'?'COMMITTEE':'MUNICIPALITY',...(role!=='CS'?{scopeId:session.user.municipalityId}:{})}} transform={b=>({...b,validFrom:new Date(String(b['validFrom'])).toISOString(),validUntil:new Date(String(b['validUntil'])).toISOString()})} fields={[{name:'userId',label:'Recipient',options:users.data?.items.filter(u=>u.enabled&&u.id!==session.user.id).map(u=>({value:u.id,label:u.displayName}))??[]},...(role==='CS'?[{name:'scopeId',label:'Committee ID'}]:[]),{name:'validFrom',label:'Valid from (your local time)',type:'datetime-local'},{name:'validUntil',label:'Expires (your local time)',type:'datetime-local'}]}/>}</AddPanel><h2>Grant requests</h2><Listing<GrantRequest> path="/admin/grant-requests">{items=><Table head={['Recipient / role','Scope','Status','Review']}>{items.map(g=><tr key={g.id}><td><strong>{users.data?.items.find(u=>u.id===g.userId)?.displayName??g.userId}</strong><small>{g.role} · Until {date(g.validUntil)}</small></td><td>{g.scopeType.toLowerCase()}<small className="mono">{g.scopeId}</small></td><td><Status value={g.state}/></td><td>{g.state==='PENDING'&&g.requestedBy!==session.user.id&&g.userId!==session.user.id?<><AddPanel label="Approve"><CommandForm title="Approve grant" path={`/admin/grant-requests/${g.id}/approve`} csrf={session.csrfToken} fields={[]} fixed={{expectedRevision:g.revision}}/></AddPanel><AddPanel label="Reject"><CommandForm title="Reject grant" path={`/admin/grant-requests/${g.id}/reject`} csrf={session.csrfToken} fields={[]} fixed={{expectedRevision:g.revision}}/></AddPanel></>:<span className="muted">{g.state==='PENDING'?'Awaiting independent review':'Review complete'}</span>}</td></tr>)}</Table>}</Listing><h2>Assigned grants</h2><Listing<Grant> path="/admin/grants">{items=><Table head={['Recipient','Role / scope','Valid until','Action']}>{items.map(g=><tr key={g.id}><td>{users.data?.items.find(u=>u.id===g.userId)?.displayName??g.userId}</td><td>{g.role}<small>{g.scopeType.toLowerCase()}</small></td><td>{date(g.validUntil)}</td><td>{g.revokedAt?<Status value="REVOKED"/>:g.userId!==session.user.id?<AddPanel label="Revoke"><CommandForm title="Revoke access immediately" path={`/admin/grants/${g.id}/revoke`} csrf={session.csrfToken} fields={[]} fixed={{expectedRevision:g.revision}}/></AddPanel>:<span className="muted">Your grant</span>}</td></tr>)}</Table>}</Listing></>;
}
function AuditPage() {return <><p className="lead">Attributable changes, preserved in sequence. Audit records cannot be edited here.</p><Listing<AuditEvent> path="/audit">{items=><Table head={['Sequence','Action / actor','Recorded','Evidence']}>{items.map(e=><tr key={e.id}><td className="mono">#{e.sequence}</td><td><strong>{e.action}</strong><small>{e.actorName}</small></td><td>{new Date(e.recordedAt).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}<small>Asia/Manila</small></td><td><details><summary>View evidence</summary><pre>{JSON.stringify({entityId:e.entityId,payload:e.payload,hash:e.hash,previousHash:e.previousHash},null,2)}</pre></details></td></tr>)}</Table>}</Listing></>;}
function Overview({session,onNavigate}:{session:SessionView;onNavigate:(v:View)=>void}) {return <><div className="welcome"><div><span className="eyebrow">A clear foundation for public service</span><h2>Every responsibility.<br/>An accountable record.</h2><p>Manage your municipal structure, maintain committee rosters, and review who can access the workspace.</p></div><div className="welcome-mark" aria-hidden="true"><Landmark size={94} strokeWidth={1}/></div></div><div className="section-title"><h2>Start with the essentials</h2><span>Platform foundation</span></div><div className="quick-grid">{navigation.filter(n=>n.id!=='overview'&&n.permission&&session.permissions.includes(n.permission)).map(n=><button className="quick-card" key={n.id} onClick={()=>onNavigate(n.id)}><n.icon size={22}/><strong>{n.label}</strong><ArrowRight size={16}/></button>)}</div><div className="foundation-note"><ShieldCheck size={24}/><div><h3>Built around accountable access</h3><p>Roles are scoped, changes are recorded, and access grants receive an independent review. Legislative case processing will arrive in a later phase.</p></div></div></>;}
export function App() {
  const cache=useQueryClient();const [view,setView]=useState<View>('overview');
  const session=useQuery({queryKey:['session'],queryFn:()=>request<{data:SessionView}>('/auth/session'),refetchInterval:60000});
  const [sessionExpired,setSessionExpired]=useState(false);
  useEffect(()=>cache.getQueryCache().subscribe(event=>{if(event.type==='updated'&&event.query.state.error instanceof ApiError&&event.query.state.error.status===401){setSessionExpired(true);}}),[cache]);
  const logout=useMutation({mutationFn:()=>request<{data:{logoutUrl:string}}>('/auth/logout',{method:'POST',csrf:session.data?.data.csrfToken}),onSuccess:result=>{cache.clear();window.location.assign(result.data.logoutUrl);}});
  if(session.isPending)return <div className="boot" role="status"><Landmark size={34}/><p>Opening your workspace…</p></div>;
  if(session.isError||!session.data||sessionExpired) return <div className="login-page"><div className="login-story"><div className="wordmark"><Landmark/> LTAS <span>LEGISLATIVE WORKSPACE</span></div><span className="eyebrow">Municipal governance, thoughtfully organized</span><h1>Good records.<br/>Clear responsibilities.<br/><em>Better continuity.</em></h1><p>A shared foundation for the people and processes behind municipal legislation.</p><div className="login-footer">Legislative Tracking and Analysis System</div></div><main className="login-card"><span className="card-icon"><ShieldCheck size={28}/></span><h2>Welcome to your workspace</h2><p>Sign in with your assigned municipal account to continue.</p>{session.isError&&!(session.error instanceof ApiError&&session.error.status===401)&&<Notice error={session.error}/>} {sessionExpired&&<p role="status">Your session ended. Sign in again to continue.</p>}<a className="primary" href="/api/v1/auth/login">Sign in securely <ArrowRight size={18}/></a><div className="login-help">Need access? Your administrator can link your identity and request the appropriate role.</div><span className="demo-label">Fictional municipality · Development environment</span></main></div>;
  const s=session.data.data;const allowed=navigation.filter(n=>!n.permission||s.permissions.includes(n.permission));
  const active=allowed.some(n=>n.id===view)?view:'overview';
  return <div className="shell"><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><div className="wordmark"><Landmark size={30}/><div>LTAS<small>LEGISLATIVE WORKSPACE</small></div></div><div className="workspace-tag"><span className="dot"/> Municipal workspace<small>Fictional development installation</small></div><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{allowed.map(n=><button key={n.id} aria-current={active===n.id?'page':undefined} className={active===n.id?'active':''} onClick={()=>setView(n.id)}><n.icon size={19}/>{n.label}{active===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={20}/><span>Accountable by design<small>Phase 1 · Foundation</small></span></div></aside><div className="main-column"><header className="topbar"><span>Municipal administration <span className="crumb">/ {active==='overview'?'Overview':labels[active]}</span></span><div className="account"><span className="avatar">{s.user.displayName.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span>{s.user.displayName}</span><button className="icon-button" aria-label="Sign out" onClick={()=>logout.mutate()} disabled={logout.isPending}><LogOut size={18}/></button></div></header><main id="main" tabIndex={-1}><div className="page-heading"><div><span className="eyebrow">LTAS / ADMINISTRATION</span><h1>{labels[active]}</h1></div><span className="demo-label">Synthetic data</span></div>{logout.isError&&<Notice error={logout.error}/>}<section className={active==='overview'?'':'content-panel'} aria-label={labels[active]}>{active==='overview'?<Overview session={s} onNavigate={setView}/>:active==='municipality'?<MunicipalityPage session={s}/>:active==='terms'?<TermsPage session={s}/>:active==='people'?<PeoplePage session={s}/>:active==='committees'?<CommitteesPage session={s}/>:active==='users'?<UsersPage session={s}/>:active==='access'?<AccessPage session={s}/>:<AuditPage/>}</section><footer className="page-footer"><span>Legislative Tracking and Analysis System</span><span>Fictional records · No official legislative decisions</span></footer></main></div></div>;
}
