// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '@testing-library/jest-dom/vitest';
import { App } from './App';
afterEach(() => {cleanup(); vi.unstubAllGlobals(); window.history.pushState({}, '', '/');});
function json(body:unknown, status = 200) {
  return {ok:status < 400, status, json:async() => body};
}
function mount() {
  return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><App/></QueryClientProvider>);
}
describe('workspace boundaries', () => {
  it('offers Keycloak login when unauthenticated, without a demo bypass', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(json({status:401, detail:'Sign in', code:'LOGIN_REQUIRED'}, 401)));
    mount();
    expect(await screen.findByRole('link', {name:/Sign In/})).toHaveAttribute('href', '/api/v1/auth/login');
    expect(screen.getByRole('heading', {name:/Welcome Back/})).toBeInTheDocument();
    expect(screen.getByRole('heading', {name:/legislative knowledge base/})).toBeInTheDocument();
    expect(screen.getByLabelText('Username')).toBeInTheDocument();
    expect(screen.getByLabelText('Password')).toBeInTheDocument();
    expect(screen.queryByRole('navigation')).not.toBeInTheDocument();
    expect(screen.queryByRole('link', {name:/demo/i})).not.toBeInTheDocument();
    expect(screen.getByRole('link', {name:/Back to home/})).toHaveAttribute('href', '/home');
  });
  it('opens the public catalog without a staff session', async () => {
    window.history.pushState({}, '', '/home');
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/public/home')) return json({data:{municipality:{name:'Municipality of Libungan', province:'North Cotabato', code:'DEMO-001'}, term:{label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30'}, stats:{measures:1, people:8, committees:2}, recentMeasures:[{id:'m1', typeCode:'ORDINANCE', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', officialSeries:null, officialYear:null, officialNumber:null, createdAt:'2026-09-22T00:00:00.000Z', authors:[{displayName:'Taylor Mendoza', role:'AUTHOR'}]}], officers:{mayor:null, viceMayor:{id:'p5', displayName:'Hayden Cruz', positionCode:'VICE_MAYOR', hasPhoto:false}, secretary:null}, note:'Demonstration public catalog'}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    expect(await screen.findByRole('heading', {name:'Legislative Tracking & Analysis System'})).toBeInTheDocument();
    expect(await screen.findByText('An Ordinance Establishing a Draft Record')).toBeInTheDocument();
    expect(screen.queryByText('Synthetic')).not.toBeInTheDocument();
    expect(screen.queryByText('Taylor Mendoza')).not.toBeInTheDocument();
    expect(screen.queryByText('Recorded stage')).not.toBeInTheDocument();
    expect(screen.getByText('Hayden Cruz')).toBeInTheDocument();
    expect(screen.getAllByText('GOVPH').length).toBeGreaterThan(0);
    expect(document.querySelector('img[src="/brand/libungan-seal.png"]')).toBeTruthy();
    expect(screen.getByRole('link', {name:'Philippine Transparency Seal'})).toHaveAttribute('href', 'https://www.libungan.gov.ph/');
    expect(screen.getAllByRole('link', {name:'Freedom of Information'}).some(link => link.getAttribute('href') === 'https://www.foi.gov.ph/')).toBe(true);
    expect(document.querySelector('img[src="/brand/foi.png"]')).toBeTruthy();
    expect(document.querySelector('img[src="/brand/bagong_pilipinas.png"]')).toBeTruthy();
    expect(screen.getByText(/not the official/i)).toBeInTheDocument();
    expect(screen.queryByRole('link', {name:/Sign in securely/})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Open catalog'}));
  });
  it('does not show administrative pages to a scoped committee user', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Casey Santos', municipalityId:'m'}, permissions:['committee.view'], csrfToken:'test'}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    expect(await screen.findByRole('navigation')).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Users & Access'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Access review'})).not.toBeInTheDocument();
    expect(screen.getAllByRole('button', {name:/Committees/}).length).toBeGreaterThan(0);
  });
  it('renders prototype workspace chrome without inventing later-phase records', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Maria Santos', municipalityId:'m'}, permissions:['committee.view','municipality.view','user.view','role.assign','audit.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    expect(await screen.findByRole('heading', {name:/Legislative Tracking & Analysis System/})).toBeInTheDocument();
    expect(screen.getByRole('button', {name:'Dashboard'})).toHaveAttribute('aria-current', 'page');
    expect(screen.getByRole('button', {name:'Legislative Measures'})).not.toBeDisabled();
    const peopleButtons = screen.getAllByRole('button', {name:'People'});
    for (const button of peopleButtons) expect(button).not.toBeDisabled();
    const committeeButtons = screen.getAllByRole('button', {name:'Committees'});
    for (const button of committeeButtons) expect(button).not.toBeDisabled();
    fireEvent.click(screen.getByRole('button', {name:'Legislative Measures'}));
    expect(await screen.findByRole('heading', {name:'Legislative Measures'})).toBeInTheDocument();
    expect(screen.getByText(/This account cannot list legislative measures/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Dashboard'}));
    expect(await screen.findByText(/Together for a Better/)).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Sessions'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'e-Library'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Reports & Analytics'})).not.toBeInTheDocument();
    expect(screen.getAllByRole('button', {name:'Users & Access'}).length).toBeGreaterThan(0);
    expect(screen.getByText(/Calendar access is not on this account/)).toBeInTheDocument();
    expect(screen.getByText('Proposed Measures')).toBeInTheDocument();
    expect(screen.getByText('Enacted Measures')).toBeInTheDocument();
    expect(screen.getByText('Pending Committee')).toBeInTheDocument();
    expect(screen.getByText('For Second Reading')).toBeInTheDocument();
    expect(screen.getByText('Awaiting Mayor Action')).toBeInTheDocument();
    expect(screen.getAllByText('0')).toHaveLength(5);
    expect(screen.queryByText('126')).not.toBeInTheDocument();
    expect(screen.queryByText('89')).not.toBeInTheDocument();
  });
  it('lets legislative staff open measures and keeps official filing hidden', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','measure.create','measure.edit','measure.submit','measure.version.create','document.upload','document.view','task.manage','notification.view','person.view','term.view','committee.view','committee.referral.view'], csrfToken:'test'}});
      if (String(url).includes('/measures/stats')) return json({data:{proposed:2, pendingCommittee:0}});
      if (String(url).includes('/referrals')) return json({items:[], pageInfo:{page:1, limit:50, total:0}});
      if (String(url).includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1, authors:[{personId:'p1', role:'AUTHOR', ordering:0, displayName:'Taylor Mendoza'}], versions:[{id:'v1', sequence:1, synopsis:'First synopsis', frozenAt:null}]}});
      if (String(url).includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/admin/terms')) return json({items:[{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/admin/persons')) return json({items:[{id:'p1', displayName:'Taylor Mendoza', positionCode:'COUNCILOR', hasPhoto:false}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    const measureButtons = await screen.findAllByRole('button', {name:'Legislative Measures'});
    expect(measureButtons.length).toBeGreaterThan(0);
    for (const button of measureButtons) expect(button).not.toBeDisabled();
    fireEvent.click(measureButtons[0]!);
    expect(await screen.findByRole('heading', {name:'Legislative Measures'})).toBeInTheDocument();
    expect(screen.getByText(/Official numbering is not configured/)).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:/File official/i})).not.toBeInTheDocument();
    expect(await screen.findByRole('heading', {name:'An Ordinance Establishing a Draft Record'})).toBeInTheDocument();
    fireEvent.click(await screen.findByRole('button', {name:'Referrals'}));
    expect(await screen.findByText(/No committee referrals recorded/)).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Record referral'})).not.toBeInTheDocument();
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Create draft'}));
    expect(screen.getByRole('dialog', {name:'New draft measure'})).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Type'), {target:{value:'RESOLUTION'}});
    fireEvent.change(screen.getByLabelText('Title'), {target:{value:'Market hours'}});
    expect(screen.queryByLabelText('Reason for this change')).not.toBeInTheDocument();
    expect(document.querySelector('input[name="reason"]')).toHaveValue('Creating new Resolution Market hours');
    expect(screen.getByLabelText('Title')).toBeInTheDocument();
    expect(screen.getByLabelText('Synopsis')).toBeInTheDocument();
    expect(screen.getByLabelText('Author')).toBeInTheDocument();
    expect(await screen.findByRole('option', {name:'2025–2028 demonstration term'})).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Council term'), {target:{value:'t'}});
    fireEvent.click(screen.getByRole('button', {name:'Add co-author'}));
    expect(screen.getByLabelText('Co-author 1')).toBeInTheDocument();
    expect(screen.getByRole('button', {name:'Remove co-author 1'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    fireEvent.click(await screen.findByRole('button', {name:'View full screen'}));
    expect(screen.getByRole('dialog', {name:'An Ordinance Establishing a Draft Record'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Exit full screen'}));
    expect(screen.queryByRole('dialog', {name:'An Ordinance Establishing a Draft Record'})).not.toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', {name:'People'})[0]!);
    expect(await screen.findByRole('heading', {name:'People'})).toBeInTheDocument();
    expect(await screen.findByText('Taylor Mendoza')).toBeInTheDocument();
    expect(screen.getByText('Councilor')).toBeInTheDocument();
    expect(screen.getByText(/not a legal seat/i)).toBeInTheDocument();
  });
  it('lets the secretary record a directory position when adding a person', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['person.view','person.manage'], csrfToken:'test'}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'People'}))[0]!);
    expect(await screen.findByRole('heading', {name:'People'})).toBeInTheDocument();
    fireEvent.click(screen.getByText('Add person'));
    expect(screen.getByLabelText('Position')).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'Mayor'})).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'Vice Mayor'})).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'Councilor'})).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'SB Secretary'})).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'SB Staff'})).toBeInTheDocument();
    expect(screen.getByRole('option', {name:'Other'})).toBeInTheDocument();
  });
  it('shows a directory photograph beside the name when one is on file', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['person.view','person.manage'], csrfToken:'test'}});
      if (String(url).includes('/admin/persons')) return json({items:[{id:'p1', displayName:'Taylor Mendoza', positionCode:'COUNCILOR', hasPhoto:true, photoVersion:'abc'}], pageInfo:{page:1, limit:25, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'People'}))[0]!);
    expect(await screen.findByText('Taylor Mendoza')).toBeInTheDocument();
    const photo = document.querySelector('img.face') as HTMLImageElement | null;
    expect(photo?.getAttribute('src')).toContain('/api/v1/admin/persons/p1/photo');
    expect(screen.getByText('Replace photo')).toBeInTheDocument();
  });
  it('opens a direct ordinance encoding form without a legislative measure', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['archive.view','archive.encode','term.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/terms')) return json({items:[{id:'t', label:'2013-2016 16th SB Council', startsOn:'2013-06-30', endsOn:'2016-06-30', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/archives/ordinances')) return json({items:[], pageInfo:{page:1, limit:50, total:0}, note:'Historical ordinance register.'});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click(await screen.findByRole('button', {name:'Ordinance archive'}));
    expect(await screen.findByRole('heading', {name:'Ordinance archive'})).toBeInTheDocument();
    expect(screen.getByText(/does not open a legislative measure/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Encode ordinance'}));
    expect(screen.getByRole('dialog', {name:'Encode ordinance'})).toBeInTheDocument();
    expect(screen.getByLabelText('Council term')).toBeInTheDocument();
    expect(screen.getByLabelText('Title')).toBeInTheDocument();
    expect(screen.getByLabelText('Where this copy came from')).toBeInTheDocument();
    expect(screen.getByText(/does not create a draft measure/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  });
  it('opens a legislative record from a person name', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['person.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/persons/p1/profile')) return json({data:{id:'p1', displayName:'Taylor Mendoza', positionCode:'COUNCILOR', hasPhoto:false, termsListed:1, authored:2, coAuthored:1, note:'Directory rows with this display name. A position label is not a certified service history. Authored counts are submitted records only.', seats:[{termId:'t', termLabel:'2025–2028 20th SB Council', startsOn:'2025-06-30', endsOn:'2028-06-30', positionCode:'COUNCILOR', authored:2, coAuthored:1, committees:[{name:'Committee on Ways and Means', role:'CHAIR', active:true}]}]}});
      if (String(url).includes('/admin/persons')) return json({items:[{id:'p1', displayName:'Taylor Mendoza', positionCode:'COUNCILOR', hasPhoto:false}], pageInfo:{page:1, limit:25, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'People'}))[0]!);
    fireEvent.click(await screen.findByRole('button', {name:'View legislative record for Taylor Mendoza'}));
    expect(await screen.findByRole('dialog', {name:'Taylor Mendoza'})).toBeInTheDocument();
    expect(await screen.findByText('Terms listed')).toBeInTheDocument();
    expect(screen.getAllByText('Authored').length).toBeGreaterThan(0);
    expect(screen.getAllByText('Co-authored').length).toBeGreaterThan(0);
    expect(screen.getByText('2025–2028 20th SB Council')).toBeInTheDocument();
    expect(screen.getByText(/Ways and Means/)).toBeInTheDocument();
    expect(screen.getByText('Active')).toBeInTheDocument();
    expect(screen.getByText(/submitted records only/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog', {name:'Taylor Mendoza'})).not.toBeInTheDocument();
  });
  it('lets committee staff open referred measures without creating drafts', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Casey Santos', municipalityId:'m'}, permissions:['municipality.view','term.view','committee.view','committee.referral.view','measure.view','document.view','task.manage','notification.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/measures/stats')) return json({data:{proposed:0, pendingCommittee:1}});
      if (String(url).includes('/referrals')) return json({items:[{id:'r1', measureId:'m1', measureVersionId:'v1', committeeId:'c1', groupId:'g1', referralSequence:1, role:'LEAD', sourceKind:'SECRETARIAT_RECORDED', referredOn:'2026-09-22', dueOn:null, disposition:'OPEN', revision:1, committee:{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance'}}], pageInfo:{page:1, limit:50, total:1}});
      if (String(url).includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1, authors:[], versions:[]}});
      if (String(url).includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Legislative Measures'}))[0]!);
    expect(await screen.findByRole('heading', {name:'Legislative Measures'})).toBeInTheDocument();
    expect(screen.getByText(/referred to your assigned committee/)).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Create draft'})).not.toBeInTheDocument();
    expect(await screen.findByRole('heading', {name:'An Ordinance Establishing a Draft Record'})).toBeInTheDocument();
    fireEvent.click(await screen.findByRole('button', {name:'Referrals'}));
    expect(await screen.findByText('Committee on Good Governance')).toBeInTheDocument();
    expect(screen.queryByRole('button', {name:'Record referral'})).not.toBeInTheDocument();
  });
  it('lets the secretary record a referral from the case file', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['measure.view','measure.create','committee.view','committee.referral.view','committee.referral.create','committee.referral.close','term.view','person.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/referrals')) return json({items:[], pageInfo:{page:1, limit:50, total:0}});
      if (String(url).includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1, authors:[], versions:[]}});
      if (String(url).includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/committees')) return json({items:[{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Legislative Measures'}))[0]!);
    fireEvent.click(await screen.findByRole('button', {name:'Referrals'}));
    fireEvent.click(await screen.findByRole('button', {name:'Record referral'}));
    expect(screen.getByRole('dialog', {name:'Record committee referral'})).toBeInTheDocument();
    expect(screen.getByLabelText('Lead committee')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog', {name:'Record committee referral'})).not.toBeInTheDocument();
  });
  it('lets the secretary open sessions, calendar, voting, and documents', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['session.view','session.manage','session.close','attendance.record','vote.view','vote.record','committee.meeting.view','document.view','document.upload','term.view','measure.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/measures/stats')) return json({data:{proposed:0, pendingCommittee:0}});
      if (String(url).includes('/admin/terms')) return json({items:[{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Sessions'}))[0]!);
    expect(await screen.findByRole('heading', {name:'Sessions'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Schedule session'}));
    expect(screen.getByRole('dialog', {name:'Schedule session'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    fireEvent.click(screen.getByRole('button', {name:'Calendar'}));
    expect(await screen.findByRole('heading', {name:'Calendar'})).toBeInTheDocument();
    expect(screen.getByText(/Not an official hearing calendar/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Voting & Attendance'}));
    expect(await screen.findByRole('heading', {name:'Voting & Attendance'})).toBeInTheDocument();
    expect(screen.getByText(/not a certified vote or quorum/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Documents'}));
    expect(await screen.findByRole('heading', {name:'Documents'})).toBeInTheDocument();
    expect(screen.getByText(/Not the e-Library/)).toBeInTheDocument();
  });
  it('lets the secretary open the e-library and reports catalog', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['library.view','report.view','measure.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/measures/stats')) return json({data:{proposed:2, pendingCommittee:1}});
      if (String(url).includes('/library')) return json({items:[{id:'m1', kind:'MEASURE', title:'An Ordinance Establishing a Draft Record', detail:'Synthetic', state:'DRAFT'}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/reports')) return json({data:{definitionVersion:'P-REPORT-INTERIM-1', asOf:'2026-09-22T00:00:00.000Z', timezone:'Asia/Manila', warnings:['These counts are an engineering catalog (P-REPORT-INTERIM-1). D-11 metric definitions are unsigned.'], metrics:[{key:'measures.proposed', label:'Proposed measures', value:2, definition:'Distinct visible measures in DRAFT or SUBMITTED. Same definition as the dashboard Proposed Measures KPI.'},{key:'referrals.pendingMeasures', label:'Pending committee', value:1, definition:'Distinct visible measures with at least one OPEN referral.'}]}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'e-Library'}))[0]!);
    expect(await screen.findByRole('heading', {name:'e-Library'})).toBeInTheDocument();
    expect(screen.getByText(/Not an official archive/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Search library'}));
    expect(await screen.findByText('An Ordinance Establishing a Draft Record')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Reports & Analytics'}));
    expect(await screen.findByRole('heading', {name:'Reports & Analytics'})).toBeInTheDocument();
    expect(screen.getByText(/Not political scoring/)).toBeInTheDocument();
    expect((await screen.findAllByText(/P-REPORT-INTERIM-1/)).length).toBeGreaterThan(0);
    expect(screen.getByText('Proposed measures')).toBeInTheDocument();
    expect(screen.getByText('Pending committee')).toBeInTheDocument();
    expect(screen.getByRole('button', {name:'Download CSV'})).toBeInTheDocument();
  });
  it('lets the secretary schedule a committee meeting and open committee documents', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['committee.view','committee.meeting.view','committee.meeting.manage','committee.meeting.close','document.view','document.upload','term.view'], csrfToken:'test'}});
      if (String(url).includes('/committees/c1/meetings')) return json({items:[], pageInfo:{page:1, limit:50, total:0}});
      if (String(url).includes('/committees/c1/documents')) return json({items:[]});
      if (String(url).includes('/committees/c1')) return json({data:{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1, term:{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}, members:[]}});
      if (String(url).includes('/committees')) return json({items:[{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Committees'}))[0]!);
    expect(await screen.findByRole('heading', {name:'Committee on Good Governance'})).toBeInTheDocument();
    fireEvent.click(await screen.findByRole('button', {name:'Meetings'}));
    fireEvent.click(await screen.findByRole('button', {name:'Schedule meeting'}));
    expect(screen.getByRole('dialog', {name:'Schedule committee meeting'})).toBeInTheDocument();
    expect(screen.getByLabelText('Title')).toBeInTheDocument();
    expect(screen.getByLabelText('Scheduled at')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog', {name:'Schedule committee meeting'})).not.toBeInTheDocument();
    expect(screen.getByText(/No committee meetings recorded/)).toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', {name:'Documents'}).at(-1)!);
    expect(await screen.findByText(/No committee documents yet/)).toBeInTheDocument();
    expect(screen.getByText('Upload committee file')).toBeInTheDocument();
  });
  it('searches live committee records from the top bar', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['committee.view','committee.manage','committee.members.manage','person.view','term.view'], csrfToken:'test'}});
      if (String(url).includes('/committees/c1')) return json({data:{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1, term:{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}, members:[]}});
      if (String(url).includes('/committees')) return json({items:[{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/admin/terms')) return json({items:[{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    const box = await screen.findByRole('combobox', {name:'Search workspace'});
    fireEvent.focus(box);
    expect(await screen.findByRole('option', {name:/Dashboard/})).toBeInTheDocument();
    fireEvent.change(box, {target:{value:'Good'}});
    expect(await screen.findByRole('option', {name:/Committee on Good Governance/})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('option', {name:/Committee on Good Governance/}));
    expect(await screen.findByRole('heading', {name:'Committees'})).toBeInTheDocument();
    fireEvent.click(await screen.findByRole('button', {name:'View full screen'}));
    expect(screen.getByRole('dialog', {name:'Committee on Good Governance'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Exit full screen'}));
    expect(screen.queryByRole('dialog', {name:'Committee on Good Governance'})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Create Committee'}));
    expect(screen.getByRole('dialog', {name:'New committee'})).toBeInTheDocument();
    expect(screen.getByLabelText('Committee name')).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    expect(screen.queryByRole('dialog', {name:'New committee'})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Members'}));
    fireEvent.click(screen.getByText('Assign committee member'));
    expect(screen.getByLabelText('End date')).toHaveValue('2028-06-30');
    expect(screen.getByLabelText('Start date')).toHaveValue('2025-07-01');
  });
  it('shows service failures instead of invented dashboard data', async () => {
    vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('Service unavailable')));
    mount();
    expect(await screen.findByRole('alert')).toHaveTextContent('Service unavailable');
  });
  it('does not invent live KPI zeros while stats are loading', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','municipality.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/measures/stats')) return new Promise(() => undefined);
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    expect(await screen.findByText(/Together for a Better/)).toBeInTheDocument();
    expect(screen.getAllByText('0')).toHaveLength(3);
    expect(screen.getAllByText('—')).toHaveLength(2);
    expect(screen.getAllByText('Loading scoped totals')).toHaveLength(2);
    expect(screen.queryByText('126')).not.toBeInTheDocument();
  });
  it('clears a search selection when the sidebar page changes', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['committee.view','committee.manage','person.view','term.view'], csrfToken:'test'}});
      if (String(url).includes('/committees/c2')) return json({data:{id:'c2', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1, term:{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}, members:[]}});
      if (String(url).includes('/committees/c1')) return json({data:{id:'c1', code:'AGRI', name:'Committee on Agriculture', termId:'t', revision:1, term:{id:'t', label:'2025–2028 demonstration term', startsOn:'2025-07-01', endsOn:'2028-06-30', revision:1}, members:[]}});
      if (String(url).includes('/committees')) return json({items:[{id:'c1', code:'AGRI', name:'Committee on Agriculture', termId:'t', revision:1},{id:'c2', code:'GOOD-GOV', name:'Committee on Good Governance', termId:'t', revision:1}], pageInfo:{page:1, limit:100, total:2}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    const box = await screen.findByRole('combobox', {name:'Search workspace'});
    fireEvent.focus(box);
    fireEvent.change(box, {target:{value:'Good'}});
    fireEvent.click(await screen.findByRole('option', {name:/Committee on Good Governance/}));
    expect(await screen.findByRole('heading', {name:'Committee on Good Governance'})).toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', {name:'Committees'})[0]!);
    expect(await screen.findByRole('heading', {name:'Committee on Agriculture'})).toBeInTheDocument();
    await waitFor(() => expect(screen.queryByRole('heading', {name:'Committee on Good Governance'})).not.toBeInTheDocument());
  });
  it('clears a searched measure when Legislative Measures is opened from the sidebar', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','measure.create'], csrfToken:'test'}});
      if (String(url).includes('/measures/m2')) return json({data:{id:'m2', typeCode:'RESOLUTION', termId:'t', title:'A Resolution On Market Hours', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1, authors:[], versions:[]}});
      if (String(url).includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1, authors:[], versions:[]}});
      if (String(url).includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1},{id:'m2', typeCode:'RESOLUTION', termId:'t', title:'A Resolution On Market Hours', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1}], pageInfo:{page:1, limit:100, total:2}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    const box = await screen.findByRole('combobox', {name:'Search workspace'});
    fireEvent.focus(box);
    fireEvent.change(box, {target:{value:'Market'}});
    fireEvent.click(await screen.findByRole('option', {name:/A Resolution On Market Hours/}));
    expect(await screen.findByRole('heading', {name:'A Resolution On Market Hours'})).toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', {name:'Legislative Measures'})[0]!);
    expect(await screen.findByRole('heading', {name:'An Ordinance Establishing a Draft Record'})).toBeInTheDocument();
    await waitFor(() => expect(screen.queryByRole('heading', {name:'A Resolution On Market Hours'})).not.toBeInTheDocument());
  });
  it('shows live KPI totals after stats load instead of placeholder dashes', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','municipality.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of San Isidro (Fictional)', province:'Demo', code:'SAN-ISIDRO', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/measures/stats')) return json({data:{proposed:2, pendingCommittee:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    expect(await screen.findByText(/Together for a Better/)).toBeInTheDocument();
    expect(await screen.findByText('Draft and submitted case files')).toBeInTheDocument();
    expect(screen.getByText('Open committee referrals')).toBeInTheDocument();
    expect(screen.getByText('2')).toBeInTheDocument();
    expect(screen.getByText('1')).toBeInTheDocument();
    expect(screen.getAllByText('0')).toHaveLength(3);
    expect(screen.queryByText('—')).not.toBeInTheDocument();
    expect(screen.queryByText('126')).not.toBeInTheDocument();
  });
  it('hides withdraw while a committee referral is open', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','measure.submit','committee.referral.view'], csrfToken:'test'}});
      if (String(url).includes('/referrals')) return json({items:[{id:'r1', measureId:'m1', measureVersionId:'v1', committeeId:'c1', groupId:'g1', referralSequence:1, role:'LEAD', sourceKind:'SECRETARIAT_RECORDED', referredOn:'2026-09-22', dueOn:null, disposition:'OPEN', revision:1, committee:{id:'c1', code:'GOOD-GOV', name:'Committee on Good Governance'}}], pageInfo:{page:1, limit:50, total:1}});
      if (String(url).includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1, authors:[], versions:[]}});
      if (String(url).includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:'v1', revision:1}], pageInfo:{page:1, limit:100, total:1}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Legislative Measures'}))[0]!);
    expect(await screen.findByRole('heading', {name:'An Ordinance Establishing a Draft Record'})).toBeInTheDocument();
    expect(await screen.findByText(/Close every open referral before withdrawing/)).toBeInTheDocument();
    expect(screen.queryByText('Withdraw')).not.toBeInTheDocument();
  });
  it('opens footer notices and offers a committee picker for staff grants', async () => {
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string) => {
      if (String(url).includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['user.view','user.manage','role.assign','municipality.view'], csrfToken:'test'}});
      if (String(url).includes('/admin/municipality')) return json({data:{id:'m', name:'Municipality of Libungan', province:'North Cotabato', code:'DEMO-001', timezone:'Asia/Manila', revision:1}});
      if (String(url).includes('/admin/grant-committees')) return json({items:[{id:'c1', name:'Committee on Good Governance', code:'GOOD-GOV', termLabel:'2025–2028'}]});
      if (String(url).includes('/admin/users')) return json({items:[{id:'other', displayName:'Reese Bautista', subject:'subject', enabled:true, revision:1}], pageInfo:{page:1, limit:100, total:1}});
      if (String(url).includes('/admin/grant-requests') || String(url).includes('/admin/grants')) return json({items:[], pageInfo:{page:1, limit:25, total:0}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click(await screen.findByRole('button', {name:'Privacy Policy'}));
    expect(await screen.findByRole('dialog', {name:'Privacy Policy'})).toBeInTheDocument();
    expect(screen.getByText(/does not publish the Municipality of Libungan privacy notice/)).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Close'}));
    fireEvent.click((await screen.findAllByRole('button', {name:'Users & Access'}))[0]!);
    fireEvent.click(await screen.findByRole('button', {name:'Access review'}));
    fireEvent.click(await screen.findByRole('button', {name:'Request access grant'}));
    expect(screen.getByRole('checkbox', {name:'Acting or emergency grant, at most 24 hours'})).not.toBeChecked();
    fireEvent.change(screen.getByLabelText('Role'), {target:{value:'CS'}});
    expect(await screen.findByLabelText('Committee')).toBeInTheDocument();
    expect(screen.queryByLabelText('Committee ID')).not.toBeInTheDocument();
    expect(await screen.findByRole('option', {name:'Committee on Good Governance · 2025–2028'})).toBeInTheDocument();
  });
  it('signs out, submits and withdraws a draft, uploads a file, and uses the keyboard', async () => {
    const calls:string[] = [];
    const assign = vi.fn();
    vi.stubGlobal('location', {assign, href:'http://localhost/', pathname:'/', search:'', hash:''});
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string, init?:RequestInit) => {
      const path = String(url);
      calls.push(`${init?.method ?? 'GET'} ${path}`);
      if (path.includes('/auth/logout')) return json({data:{logoutUrl:'http://localhost:8081/logout'}});
      if (path.includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Riley Flores', municipalityId:'m'}, permissions:['measure.view','measure.create','measure.submit','document.upload','document.view','term.view','person.view'], csrfToken:'test'}});
      if (path.includes('/measures/m2')) return json({data:{id:'m2', typeCode:'RESOLUTION', termId:'t', title:'A Second Draft', subject:'Later', stage:'SUBMITTED', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:2, authors:[], versions:[]}});
      if (path.includes('/measures/m1')) return json({data:{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1, authors:[], versions:[]}});
      if (path.includes('/measures')) return json({items:[{id:'m1', typeCode:'ORDINANCE', termId:'t', title:'An Ordinance Establishing a Draft Record', subject:'Synthetic', stage:'DRAFT', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:1},{id:'m2', typeCode:'RESOLUTION', termId:'t', title:'A Second Draft', subject:'Later', stage:'SUBMITTED', classification:'INTERNAL', officialSeries:null, officialYear:null, officialNumber:null, currentVersionId:null, revision:2}], pageInfo:{page:1, limit:100, total:2}});
      if (path.includes('/documents/intents') && path.includes('/content')) return json({data:{id:'up1', bytes:4, sha256:'abc'}});
      if (path.includes('/documents/intents') && path.includes('/finalize')) return json({data:{id:'doc1'}});
      if (path.includes('/documents/intents')) return json({data:{id:'up1'}});
      if (path.includes('/measures/m1/submit') || path.includes('/measures/m2/withdraw')) return json({data:{id:'m1', revision:2}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Legislative Measures'}))[0]!);
    fireEvent.keyDown(await screen.findByRole('row', {name:'A Second Draft'}), {key:'Enter'});
    expect(await screen.findByRole('heading', {name:'A Second Draft'})).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', {name:'Withdraw'}));
    fireEvent.click(screen.getByRole('dialog', {name:'Withdraw'}).querySelector('button.primary') as HTMLButtonElement);
    await waitFor(() => expect(calls.some(call => call.startsWith('POST') && call.includes('/measures/m2/withdraw'))).toBe(true));
    fireEvent.keyDown(screen.getByRole('row', {name:'An Ordinance Establishing a Draft Record'}), {key:'Enter'});
    fireEvent.click(await screen.findByRole('button', {name:'Submit for secretariat review'}));
    fireEvent.click(screen.getByRole('button', {name:'Submit draft'}));
    await waitFor(() => expect(calls.some(call => call.startsWith('POST') && call.includes('/measures/m1/submit'))).toBe(true));
    fireEvent.click(screen.getByRole('button', {name:'Create draft'}));
    expect(screen.getByRole('dialog', {name:'New draft measure'})).toBeInTheDocument();
    fireEvent.keyDown(document, {key:'Escape'});
    expect(screen.queryByRole('dialog', {name:'New draft measure'})).not.toBeInTheDocument();
    fireEvent.click(screen.getAllByRole('button', {name:'Documents'})[1]!);
    fireEvent.click(await screen.findByRole('button', {name:'Upload supporting file'}));
    const file = new File(['%PDF'], 'note.pdf', {type:'application/pdf'});
    const input = screen.getByLabelText('File') as HTMLInputElement;
    Object.defineProperty(input, 'files', {value:[file]});
    fireEvent.change(input);
    fireEvent.submit(input.closest('form')!);
    await waitFor(() => expect(calls.some(call => call.includes('/documents/intents') && call.includes('/finalize'))).toBe(true));
    fireEvent.click(screen.getByRole('button', {name:'Sign out'}));
    await waitFor(() => expect(assign).toHaveBeenCalledWith('http://localhost:8081/logout'));
  });
  it('records attendance and a tally from the voting page', async () => {
    const calls:string[] = [];
    vi.stubGlobal('fetch', vi.fn().mockImplementation(async (url:string, init?:RequestInit) => {
      const path = String(url);
      calls.push(`${init?.method ?? 'GET'} ${path}`);
      if (path.includes('/auth/session')) return json({data:{user:{id:'u', displayName:'Jamie Cruz', municipalityId:'m'}, permissions:['session.view','attendance.record','vote.view','vote.record','person.view'], csrfToken:'test'}});
      if (path.includes('/sessions/s1')) return json({data:{id:'s1', termId:'t', reference:'S-2026-1', title:'Regular sitting', venue:'Hall', kind:'REGULAR', scheduledAt:'2026-09-22T02:00:00.000Z', state:'SCHEDULED', revision:3, agenda:[{id:'a1', sequence:1, measureId:'m1', measureVersionId:'v1', measure:{id:'m1', title:'An Ordinance Establishing a Draft Record', typeCode:'ORDINANCE', stage:'SUBMITTED'}}], attendance:[], votes:[]}});
      if (path.includes('/sessions')) return json({items:[{id:'s1', termId:'t', reference:'S-2026-1', title:'Regular sitting', venue:'Hall', kind:'REGULAR', scheduledAt:'2026-09-22T02:00:00.000Z', state:'SCHEDULED', revision:3}], pageInfo:{page:1, limit:50, total:1}});
      if (path.includes('/admin/persons')) return json({items:[{id:'p1', displayName:'Taylor Mendoza', positionCode:'COUNCILOR', hasPhoto:false}], pageInfo:{page:1, limit:100, total:1}});
      if (path.includes('/attendance') || path.includes('/votes')) return json({data:{id:'s1', revision:4}});
      return json({items:[], pageInfo:{page:1, limit:25, total:0}});
    }));
    mount();
    fireEvent.click((await screen.findAllByRole('button', {name:'Voting & Attendance'}))[0]!);
    fireEvent.click(await screen.findByRole('row', {name:'Regular sitting'}));
    fireEvent.click(await screen.findByRole('button', {name:'Record attendance'}));
    expect(await screen.findByRole('option', {name:'Taylor Mendoza · Councilor'})).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('Person'), {target:{value:'p1'}});
    fireEvent.change(screen.getByLabelText('Disposition'), {target:{value:'PRESENT'}});
    fireEvent.click(screen.getByRole('button', {name:'Save attendance'}));
    await waitFor(() => expect(calls.some(call => call.includes('/sessions/s1/attendance'))).toBe(true));
    fireEvent.click(await screen.findByRole('button', {name:'Record tally'}));
    fireEvent.change(screen.getByLabelText('Agenda measure'), {target:{value:'m1'}});
    fireEvent.change(screen.getByLabelText('Yes'), {target:{value:'5'}});
    fireEvent.change(screen.getByLabelText('No'), {target:{value:'1'}});
    fireEvent.change(screen.getByLabelText('Abstain'), {target:{value:'0'}});
    fireEvent.click(screen.getByRole('button', {name:'Save tally'}));
    await waitFor(() => expect(calls.some(call => call.includes('/sessions/s1/votes'))).toBe(true));
  });
});
